Repository nanoframework/nf-tools, pull requests merged in 2021-02, with the labels that each got.

#22 Add csproj filter to update dependencies script
  github-actions/update-nf-dependencies.ps1
Labels: Area: Config-and-Build, Type: enhancement

#23 Fixes environment variables for nuget github action.
  github-actions/update-nf-dependencies.ps1
Labels: Area: Config-and-Build

#24 Refactor update process.
  github-actions/update-nf-dependencies.ps1
Labels: Area: Config-and-Build, Type: dependencies

#25 Add parameter for nuget release type
  github-actions/update-nf-dependencies.ps1
Labels: Area: Config-and-Build, Type: dependencies

#26 Work update dependencies ps1
  github-actions/update-nf-dependencies.ps1
Labels: Area: Config-and-Build
